---
# tasks file for windows
- name: Find Hostname
  win_shell: hostname
  register: host
#  when: port_out is success
  ignore_errors: true

- name: Set variable for Hostname
  set_fact:
    host_name: "{{ host.stdout_lines }}"
#  when: port_out is success
  ignore_errors: true

- name: Print host name
  debug:
    msg: "{{ host_name }}"
#  when: port_out is success
  ignore_errors: true

